spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/testbbl}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/testbbl}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    locations: classpath:db/migration

