spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: ""
  flyway:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    user: sa
    password: ""
    locations: classpath:db/migration
  main:
    web-application-type: reactive

